### ISSUE TITLE
compilation error for libraries/FMWPC/DCTOFPoint_factory.cc

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/halld_recon#600]
The following error is seen in the nightly build on jlabl5 only. That node is running RHEL8. The error shown is from an interactive re-try of the nightly build.

[nightly_build_error.txt](https://github.com/JeffersonLab/halld_recon/files/7530953/nightly_build_error.txt)

**Comment by staylorjlab** [comment]
Looks like #include <cmath> is needed now?  I would check this but on jlabl5 I can't find scons...??

Simon

________________________________
From: Mark M. Ito ***@***.***>
Sent: Friday, November 12, 2021 6:43 PM
To: JeffersonLab/halld_recon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [JeffersonLab/halld_recon] compilation error for libraries/FMWPC/DCTOFPoint_factory.cc (Issue #600)


The following error is seen in the nightly build on jlabl5 only. That node is running RHEL8. The error shown is from an interactive re-try of the nightly build.

nightly_build_error.txt<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_files_7530953_nightly-5Fbuild-5Ferror.txt&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=-OqssvRvRqB76_WgPxaGf00Ynk6tLY-9A8YMYvvMGMI&m=R7CkpR7nFZ4oPOUa5z3rQGfCGteyOATb2dhuyKxMNhVl9Hcr11ni35V9KAj85bBj&s=yPx-IdO-h2Ofxkm9B2aHsVZBQupzFXKlwH_7ivROYZQ&e=>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_halld-5Frecon_issues_600&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=-OqssvRvRqB76_WgPxaGf00Ynk6tLY-9A8YMYvvMGMI&m=R7CkpR7nFZ4oPOUa5z3rQGfCGteyOATb2dhuyKxMNhVl9Hcr11ni35V9KAj85bBj&s=iuM9l0ebUaslUWLwmsDMrJDGUDW_A--7XG5HAYTpsD8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADFJEUEKTBVNOHCA5KG75P3ULWRBLANCNFSM5H543ZOQ&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=-OqssvRvRqB76_WgPxaGf00Ynk6tLY-9A8YMYvvMGMI&m=R7CkpR7nFZ4oPOUa5z3rQGfCGteyOATb2dhuyKxMNhVl9Hcr11ni35V9KAj85bBj&s=ezw5AE8QBBR0tOKtj7_jZDJfX-5XnwgHDlKZAHLP1wQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=-OqssvRvRqB76_WgPxaGf00Ynk6tLY-9A8YMYvvMGMI&m=R7CkpR7nFZ4oPOUa5z3rQGfCGteyOATb2dhuyKxMNhVl9Hcr11ni35V9KAj85bBj&s=KmZ6TfK2QZVuGRr8MsklvSRRvrJAJ78BfiL45pyCr_w&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=-OqssvRvRqB76_WgPxaGf00Ynk6tLY-9A8YMYvvMGMI&m=R7CkpR7nFZ4oPOUa5z3rQGfCGteyOATb2dhuyKxMNhVl9Hcr11ni35V9KAj85bBj&s=NKSXWpOOuIsgqSjGuNALJkcZ0rJMHOT4mTYyeTTpCaU&e=>.

**Comment by markito3** [comment]
Yes. You can't find scons. On jlabl5 the command "scons" does not exist. If you look at [night_build_error.txt ](https://github.com/JeffersonLab/halld_recon/files/7530953/nightly_build_error.txt), you see that the correct command is:

`scons-3 install PYTHONCOMMAND=python3 SHOWBUILD=1`

and please, don't blame the messenger.

**Comment by aaust** [comment]
Looks like this has been solved by PR #609
