### ISSUE TITLE
ERROR: MULTIPLE DREACTIONS WITH THE SAME NAME(S):

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/halld_recon#625]
I have this error for the following processes:

Reaction1 1_13__1_1_13
Reaction1:Flags B4
Reaction2 1_14__1_1_14
Reaction2:Flags B4

Could the DREACTIONS naming be the full reaction process and not only the final state?

**Comment by aaust** [comment]
That is useful for all nuclear target experiments. I suggest to add the target explicitly if it is not a proton in order to keep the current naming scheme for GlueX. Your reactions would then look like this:

ReactionFilter: Reaction: gn_ggn__B4
Photon_Neutron__Photon_Photon_Neutron
ReactionFilter: Reaction: gg__B4
Photon_Proton__Photon_Photon_Proton

**Comment by igjaegle** [comment]
Sounds good.

**Comment by aaust** [comment]
Yes, I included the full initial state if the target is not a proton. Please have a look at PR #626 .
